version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: ghcr.io/develang/todo:latest
    ports:
      - 80:8000
    depends_on:
      - db
volumes:
  postgres_data:
